import React from 'react';
import { ConsentReceipt } from '@/types/document.types';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { formatDate } from '@/utils/formatDate';
import { FileCheck, Download, ShieldCheck, Clock, FileKey } from 'lucide-react';

export interface ConsentReceiptCardProps {
  receipt: ConsentReceipt;
}

export const ConsentReceiptCard: React.FC<ConsentReceiptCardProps> = ({ receipt }) => {
  const handleDownloadPdf = () => {
    // Generate synthetic downloadable receipt text/pdf
    const receiptContent = `=================================================================
DOCUMENT SHARING CONSENT RECEIPT (SDIIL ICJS)
=================================================================
Receipt Event ID:  ${receipt.event_id}
Generated at (UTC): ${receipt.timestamp}
Valid Until:       ${receipt.valid_until}

DOCUMENT REFERENCE:
Document ID:       ${receipt.doc_id}
Document Title:    ${receipt.doc_title || 'Classified Evidence File'}
Case ID:           ${receipt.case_id}

AUTHORIZATION PROVENANCE:
Initiator:         ${receipt.initiator_name} (ID: ${receipt.initiator_id})
Recipient:         ${receipt.recipient_name || receipt.recipient_role}
Approver:          ${receipt.approver_name || 'Not Required (Level B/C)'}
Share Justification: ${receipt.share_reason}

CRYPTOGRAPHIC INTEGRITY:
Receipt SHA-256:   ${receipt.receipt_hash}
System RSA Sig:    ${receipt.receipt_signature}

STATEMENT:
This document was shared under authorized statutory consent.
Any unauthorized further distribution is a strict violation of evidence handling protocols.
=================================================================
Generated by SDIIL Sensitive Document Intelligence and Integrity Layer`;

    const blob = new Blob([receiptContent], { type: 'text/plain;charset=utf-8' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Consent_Receipt_${receipt.event_id}.txt`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  return (
    <Card className="border-accent-success/40 bg-accent-success/5 space-y-3">
      <div className="flex items-center justify-between pb-2 border-b border-border">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-full bg-accent-success/20 border border-accent-success/40 flex items-center justify-center text-accent-success shrink-0">
            <FileCheck className="w-4 h-4" />
          </div>
          <div>
            <span className="text-[10px] font-mono text-accent-success uppercase tracking-wider font-semibold">
              Verifiable Consent Artifact
            </span>
            <h4 className="text-sm font-semibold text-text-primary">
              Document Sharing Consent Receipt
            </h4>
          </div>
        </div>

        <Button
          size="sm"
          variant="secondary"
          onClick={handleDownloadPdf}
          leftIcon={<Download className="w-3.5 h-3.5" />}
        >
          Download Receipt
        </Button>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs bg-bg-secondary p-3 rounded-card border border-border">
        <div>
          <span className="text-text-muted">Target Recipient:</span>
          <span className="font-semibold text-text-primary block mt-0.5">
            {receipt.recipient_name || receipt.recipient_role}
          </span>
        </div>

        <div>
          <span className="text-text-muted">Supervisor Authorization:</span>
          <span className="font-semibold text-accent-success block mt-0.5">
            {receipt.approver_name || 'Standard Approval Confirmed'}
          </span>
        </div>

        <div>
          <span className="text-text-muted flex items-center gap-1">
            <Clock className="w-3 h-3" /> Expiry Schedule:
          </span>
          <span className="text-text-primary font-mono block mt-0.5">
            Valid until {formatDate(receipt.valid_until)}
          </span>
        </div>

        <div>
          <span className="text-text-muted flex items-center gap-1">
            <ShieldCheck className="w-3 h-3" /> Issued Timestamp:
          </span>
          <span className="text-text-primary font-mono block mt-0.5">
            {formatDate(receipt.timestamp)}
          </span>
        </div>

        <div className="sm:col-span-2 pt-1 border-t border-border font-mono text-[10px] text-text-muted space-y-1">
          <div className="flex items-center justify-between">
            <span className="flex items-center gap-1">
              <FileKey className="w-3 h-3" /> Receipt Hash:
            </span>
            <span className="text-text-secondary truncate max-w-[280px] sm:max-w-md select-all">
              {receipt.receipt_hash}
            </span>
          </div>
          <div className="flex items-center justify-between">
            <span>RSA Signature:</span>
            <span className="text-text-secondary truncate max-w-[280px] sm:max-w-md select-all">
              {receipt.receipt_signature}
            </span>
          </div>
        </div>
      </div>

      <p className="text-[11px] text-text-muted italic leading-relaxed">
        * Access grant recorded to <code className="text-accent-primary">abac_policies</code>. The recipient will be audited on first open.
      </p>
    </Card>
  );
};
