import React from 'react';
import { RAGSearchResponse } from '@/types/document.types';
import { CitationChip } from './CitationChip';
import { Alert } from '@/components/ui/Alert';
import { Card } from '@/components/ui/Card';
import { Bot, CheckCircle2, ShieldAlert, Sparkles, Layers } from 'lucide-react';

export interface SearchResultProps {
  result: RAGSearchResponse;
  onSelectDoc?: (docId: string) => void;
}

export const SearchResult: React.FC<SearchResultProps> = ({ result, onSelectDoc }) => {
  return (
    <div className="space-y-4">
      {/* Mandatory Human Verification Banner (rule-ai-output-requires-human-verification-flag) */}
      <Alert variant="ai-verification" title="Human Verification Required (ICJS Standard)">
        This output was generated by the ABAC-Gated RAG Engine and requires human verification
        by an authorized officer before any legal or investigative use. AI outputs must never be
        treated as final legal determinations.
      </Alert>

      {/* Synthesis Answer Card */}
      <Card className="space-y-4">
        <div className="flex items-center justify-between pb-3 border-b border-border">
          <div className="flex items-center gap-2 text-sm font-semibold text-text-primary">
            <Bot className="w-4 h-4 text-accent-primary" />
            <span>ABAC-Filtered Intelligence Answer</span>
          </div>

          <div className="flex items-center gap-2 text-xs">
            <span className="inline-flex items-center gap-1 text-text-muted bg-bg-elevated px-2 py-0.5 rounded border border-border">
              <Layers className="w-3 h-3" />
              {result.chunks_used_count} Authorized Chunks
            </span>
            {result.flags.citation_hallucinated ? (
              <span className="inline-flex items-center gap-1 text-accent-danger bg-accent-danger/10 px-2 py-0.5 rounded border border-accent-danger/30 font-medium">
                <ShieldAlert className="w-3 h-3" />
                Hallucination Flagged
              </span>
            ) : (
              <span className="inline-flex items-center gap-1 text-accent-success bg-accent-success/10 px-2 py-0.5 rounded border border-accent-success/30 font-medium">
                <CheckCircle2 className="w-3 h-3" />
                Citations Verified
              </span>
            )}
          </div>
        </div>

        {/* Formatted Answer Body */}
        <div className="text-body text-text-primary leading-relaxed whitespace-pre-line bg-bg-secondary/60 p-4 rounded-card border border-border/80">
          {result.answer}
        </div>

        {/* Source Citations */}
        {result.citations.length > 0 && (
          <div className="pt-2">
            <span className="text-label text-text-muted flex items-center gap-1.5 mb-2.5">
              <Sparkles className="w-3.5 h-3.5 text-accent-primary" />
              Authorized Source Citations (Click to inspect)
            </span>
            <div className="flex flex-wrap gap-2">
              {result.citations.map((c) => (
                <CitationChip key={c.chunk_id} citation={c} onClick={onSelectDoc} />
              ))}
            </div>
          </div>
        )}

        {/* Audit anchor footnote */}
        <div className="pt-2 border-t border-border flex items-center justify-between text-[11px] font-mono text-text-muted">
          <span>Query Reference: {result.query_id}</span>
          <span>Logged to Audit Trail at {new Date(result.query_timestamp).toLocaleTimeString()}</span>
        </div>
      </Card>
    </div>
  );
};
