import React, { useState } from 'react';
import { TamperVerificationResult } from '@/types/document.types';
import { Button } from '@/components/ui/Button';
import { Download, FileText } from 'lucide-react';

export interface ReportDownloadProps {
  result: TamperVerificationResult;
}

import { verificationService } from '@/services/verification.service';

export const ReportDownload: React.FC<ReportDownloadProps> = ({ result }) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const handleDownloadReport = async () => {
    setIsGenerating(true);
    setErrorMsg(null);
    try {
      await verificationService.downloadVerificationReport(
        result.doc_id,
        result.version_number,
        result.doc_title,
        result.verification_status === 'TAMPERED' || !result.hashes_match
      );
    } catch (err: any) {
      console.error('[ReportDownload] Backend PDF generation failed, falling back to text format:', err);
      // Fallback text report
      const content = `================================================================================
INTEGRATED CRIMINAL JUSTICE SYSTEM (ICJS) — EVIDENCE VAULT
STATUTORY TAMPER VERIFICATION REPORT & CRYPTOGRAPHIC CERTIFICATE
================================================================================
Generated At (UTC): ${result.generated_at}
Document Identifier: ${result.doc_id}
Case Reference:      ${result.case_number || result.case_id}
Document Title:      ${result.doc_title || 'N/A'}
Version Number:      ${result.version_number || 1}
Overall Status:      ${result.verification_status}

--------------------------------------------------------------------------------
VERIFICATION DETERMINATION
--------------------------------------------------------------------------------
STATUS DETERMINATION: ${result.verification_status === 'VERIFIED' ? '[ VERIFIED — EVIDENCE INTACT ]' : '[ TAMPER DETECTED — COMPROMISED ]'}
Hashes Match:         ${result.hashes_match ? 'TRUE' : 'FALSE'}
Registered Hash:      ${result.registered_hash || result.original_hash}
Recomputed Hash:      ${result.computed_hash}

Total Blockchain Anchor Events: ${result.blockchain_events_count}
Total Audit Log Trail Entries:  ${result.audit_events_count}
Total Statutory Sharing Events: ${result.sharing_events_count}

STATUTORY DISCLAIMER & HUMAN VERIFICATION NOTICE:
This report demonstrates document integrity since initial electronic intake.
It does not constitute legal proof of document truthfulness or evidentiary validity.
Human verification by presiding judicial officers or prosecutors is strictly required.
================================================================================
Generated by SDIIL Sensitive Document Intelligence and Integrity Layer`;

      const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `ICJS_Court_Verification_Report_${result.doc_id}_v${result.version_number || 1}.txt`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="flex items-center justify-between p-4 rounded-card bg-bg-card border border-border">
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-full bg-accent-primary/15 border border-accent-primary/30 flex items-center justify-center text-accent-primary shrink-0">
          <FileText className="w-5 h-5" />
        </div>
        <div>
          <h4 className="text-sm font-semibold text-text-primary">
            Court-Ready Tamper Verification Report
          </h4>
          <p className="text-xs text-text-secondary mt-0.5">
            Cryptographically sealed report containing full blockchain timeline, hash comparison, and QR resolution.
          </p>
          {errorMsg && (
            <p className="text-xs text-accent-danger mt-1">
              {errorMsg}
            </p>
          )}
        </div>
      </div>

      <Button
        variant="primary"
        size="md"
        isLoading={isGenerating}
        onClick={handleDownloadReport}
        leftIcon={<Download className="w-4 h-4" />}
      >
        Download Court Report
      </Button>
    </div>
  );
};
